export const dashboardRoutes = {
  reportedWebsites: '/moderation-url-entreprises',
  reportedCompanyWebsites: '/moderation-url-entreprises/site-internet',
  reportedWebsites_unknown: '/moderation-url-entreprises/sites-internet/non-identifies',
  reportedPhone: '/suivi-des-telephones',
  reports: '/suivi-des-signalements',
  subscriptions: '/abonnements',
  report: (id: string = ':id') => `/suivi-des-signalements/report/${id}`,
  exports: '/mes-telechargements',
  companies: '/entreprises',
  companiesPro: '/mes-entreprises',
  companyAccesses: (siret: string = ':siret') => `/entreprise/acces/${siret}`,
  companies_toActivate: '/entreprises/a-activer',
  companies_registered: '/entreprises/les-plus-signalees',
  users: '/admin/invitation-ccrf',
  users_pending: '/admin/invitation-ccrf/pending',
  users_all: '/admin/invitation-ccrf/all',
  settings: '/parametres',
  register: '/activation',
  registerBis: '/entreprise/activation',
  login: '/connexion',
  emailValidation: '/connexion/validation-email',
  resetPassword: (token: string = ':token') => `/connexion/nouveau-mot-de-passe/${token}`,
  modeEmploiDGCCRF: '/mode-emploi-dgccrf',
  consumerReview: (reportId: string = ':reportId') => `/suivi-des-signalements/${reportId}/avis`,
};

